"""empty message

Revision ID: 486959a63c65
Revises: d1b95c89f113
Create Date: 2021-12-16 12:38:41.520263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486959a63c65'
down_revision = 'd1b95c89f113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
